name: Code Tests

on: push

jobs:
  running-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: Run tests
        run: |
          pip install .
          pip install pytest
          python3 -m pytest .
